/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.khaled.clientbsitter.model.enums;

/**
 *
 * @author alibi
 */
public enum Pays {
Afghanistan("Afghanistan"),
Albania("Albania"),
Algeria("Algeria"),
Andorra("Andorra"),
Angola("Angola"),
AntiguaDeps("Antigua & Deps"),
Argentina("Argentina"),
Armenia("Armenia"),
Australia("Australia"),
Austria("Austria"),
Azerbaijan("Azerbaijan"),
Bahamas("Bahamas"),
Bahrain("Bahrain"),
Bangladesh("Bangladesh"),
Barbados("Barbados"),
Belarus("Belarus"),
Belgium("Belgium"),
Belize("Belize"),
Benin("Benin"),
Bhutan("Bhutan"),
Bolivia("Bolivia"),
BosniaHerzegovina("Bosnia Herzegovina"),
Botswana("Botswana"),
Brazil("Brazil"),
Brunei("Brunei"),
Bulgaria("Bulgaria"),
Burkina("Burkina"),
Burundi("Burundi"),
Cambodia("Cambodia"),
Cameroon("Cameroon"),
Canada("Canada"),
CapeVerde("Cape Verde"),
CentralAfricanRep("Central African Rep"),
Chad("Chad"),
Chile("Chile"),
China("China"),
Colombia("Colombia"),
Comoros("Comoros"),
Congo("Congo"),
CongoDR("Congo {Democratic Rep}"),
CostaRica("Costa Rica"),
Croatia("Croatia"),
Cuba("Cuba"),
Cyprus("Cyprus"),
CzechRepublic("Czech Republic"),
Denmark("Denmark"),
Djibouti("Djibouti"),
Dominica("Dominica"),
DominicanRepublic("Dominican Republic"),
EastTimor("East Timor"),
Ecuador("Ecuador"),
Egypt("Egypt"),
ElSalvador("El Salvador"),
EquatorialGuinea("Equatorial Guinea"),
Eritrea("Eritrea"),
Estonia("Estonia"),
Ethiopia("Ethiopia"),
Fiji("Fiji"),
Finland("Finland"),
France("France"),
Gabon("Gabon"),
Gambia("Gambia"),
Georgia("Georgia"),
Germany("Germany"),
Ghana("Ghana"),
Greece("Greece"),
Grenada("Grenada"),
Guatemala("Guatemala"),
Guinea("Guinea"),
GuineaBissau("Guinea-Bissau"),
Guyana("Guyana"),
Haiti("Haiti"),
Honduras("Honduras"),
Hungary("Hungary"),
Iceland("Iceland"),
India("India"),
Indonesia("Indonesia"),
Iran("Iran"),
Iraq("Iraq"),
IrelandRepublic("Ireland {Republic}"),
Israel("Israel"),
Italy("Italy"),
IvoryCoast("Ivory Coast"),
Jamaica("Jamaica"),
Japan("Japan"),
Jordan("Jordan"),
Kazakhstan("Kazakhstan"),
Kenya("Kenya"),
Kiribati("Kiribati"),
KoreaNorth("Korea North"),
KoreaSouth("Korea South"),
Kosovo("Kosovo"),
Kuwait("Kuwait"),
Kyrgyzstan("Kyrgyzstan"),
Laos("Laos"),
Latvia("Latvia"),
Lebanon("Lebanon"),
Lesotho("Lesotho"),
Liberia("Liberia"),
Libya("Libya"),
Liechtenstein("Liechtenstein"),
Lithuania("Lithuania"),
Luxembourg("Luxembourg"),
Macedonia("Macedonia"),
Madagascar("Madagascar"),
Malawi("Malawi"),
Malaysia("Malaysia"),
Maldives("Maldives"),
Mali("Mali"),
Malta("Malta"),
MarshallIslands("Marshall Islands"),
Mauritania("Mauritania"),
Mauritius("Mauritius"),
Mexico("Mexico"),
Micronesia("Micronesia"),
Moldova("Moldova"),
Monaco("Monaco"),
Mongolia("Mongolia"),
Montenegro("Montenegro"),
Morocco("Morocco"),
Mozambique("Mozambique"),
MyanmarBurma("Myanmar, {Burma}"),
Namibia("Namibia"),
Nauru("Nauru"),
Nepal("Nepal"),
Netherlands("Netherlands"),
NewZealand("New Zealand"),
Nicaragua("Nicaragua"),
Niger("Niger"),
Nigeria("Nigeria"),
Norway("Norway"),
Oman("Oman"),
Pakistan("Pakistan"),
Palau("Palau"),
Panama("Panama"),
PapuaNewGuinea("Papua New Guinea"),
Paraguay("Paraguay"),
Peru("Peru"),
Philippines("Philippines"),
Poland("Poland"),
Portugal("Portugal"),
Qatar("Qatar"),
Romania("Romania"),
RussianFederation("Russian Federation"),
Rwanda("Rwanda"),
StKittsNevis("St Kitts & Nevis"),
StLucia("St Lucia"),
SaintVincenttheGrenadines("Saint Vincent & the Grenadines"),
Samoa("Samoa"),
SanMarino("San Marino"),
SaoTomePrincipe("Sao Tome & Principe"),
SaudiArabia("Saudi Arabia"),
Senegal("Senegal"),
Serbia("Serbia"),
Seychelles("Seychelles"),
SierraLeone("Sierra Leone"),
Singapore("Singapore"),
Slovakia("Slovakia"),
Slovenia("Slovenia"),
SolomonIslands("Solomon Islands"),
Somalia("Somalia"),
SouthAfrica("South Africa"),
SouthSudan("South Sudan"),
Spain("Spain"),
SriLanka("Sri Lanka"),
Sudan("Sudan"),
Suriname("Suriname"),
Swaziland("Swaziland"),
Sweden("Sweden"),
Switzerland("Switzerland"),
Syria("Syria"),
Taiwan("Taiwan"),
Tajikistan("Tajikistan"),
Tanzania("Tanzania"),
Thailand("Thailand"),
Togo("Togo"),
Tonga("Tonga"),
TrinidadTobago("Trinidad & Tobago"),
Tunisia("Tunisia"),
Turkey("Turkey"),
Turkmenistan("Turkmenistan"),
Tuvalu("Tuvalu"),
Uganda("Uganda"),
Ukraine("Ukraine"),
UnitedArabEmirates("United Arab Emirates"),
UnitedKingdom("United Kingdom"),
UnitedStates("United States"),
Uruguay("Uruguay"),
Uzbekistan("Uzbekistan"),
Vanuatu("Vanuatu"),
VaticanCity("Vatican City"),
Venezuela("Venezuela"),
Vietnam("Vietnam"),
Yemen("Yemen"),
Zambia("Zambia"),
Zimbabwe("Zimbabwe");

   private String pays;
 
    Pays(String pays) {
        this.pays = pays;
    }
 
    public String getPays() {
        return pays;
    }
}
